#!/usr/bin/env python3
"""Build the source registry and planning estimate for a global lubricants catalog."""

from __future__ import annotations

from datetime import date
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "deliverables" / "Global_lubricants_catalog_registry.xlsx"


SOURCES = [
    ("JASO 4T filed oils", "Global filed list", "Official PDF registry", "https://www.jalos.or.jp/onfile/pdf/4T_EV_LIST.pdf", 2612, "filed rows", "List dated 2026-07-01; 2,611 unique oil codes", "ingested_and_verified"),
    ("JASO diesel filed oils", "Global filed list", "Official PDF registry", "https://www.jalos.or.jp/onfile/pdf/DEO_EV_LIST.pdf", 419, "filed rows", "List dated 2026-07-01; 419 unique oil codes", "ingested_and_verified"),
    ("JASO 2T filed oils", "Global filed list", "Official PDF registry", "https://www.jalos.or.jp/onfile/pdf/2T_EV_LIST.pdf", 599, "filed rows", "List dated 2026-07-01; 599 unique oil codes", "ingested_and_verified"),
    ("NMMA TC-W3", "Global licensed list", "Official marine-oil registry", "https://www.nmma.org/certification/oil/tc-w3", 137, "licensed products", "2026 registered two-stroke-cycle marine oils", "ingested_and_verified"),
    ("NMMA FC-W", "Global licensed list", "Official marine-oil registry", "https://www.nmma.org/certification/oil/fc-w", 35, "licensed products", "2026 registered four-stroke-cycle marine oils", "ingested_and_verified"),
    ("NMMA FC-W(CAT)", "Global licensed list", "Official marine-oil registry", "https://www.nmma.org/certification/oil/fc-wcat", 3, "licensed products", "2026 catalyst-compatible marine oils", "ingested_and_verified"),
    ("GM dexos1 Gen3", "Global licensed list", "Official OEM licensing registry", "https://www.gmdexos.com/brands/dexos1_3/index.html", 1575, "licensed product rows", "Includes supplier, viscosity and GM licence number", "ingested_and_verified"),
    ("GM dexos2", "Global licensed list", "Official OEM licensing registry", "https://www.gmdexos.com/brands/dexos2/index.html", 81, "licensed product rows", "One source licence-number collision retained explicitly", "ingested_and_verified"),
    ("GM dexosD", "Global licensed list", "Official OEM licensing registry", "https://www.gmdexos.com/brands/dexosd/index.html", 41, "licensed product rows", "Includes supplier, viscosity and GM licence number", "ingested_and_verified"),
    ("GM dexosR", "Global licensed list", "Official OEM licensing registry", "https://www.gmdexos.com/brands/dexosr/index.html", 8, "licensed product rows", "Includes supplier, viscosity and GM licence number", "ingested_and_verified"),
    ("NLGI certified products", "Global licensed list", "Official grease certification registry", "https://www.nlgi.org/about-us/high-performance-multiuse-grease/", 279, "certified product rows", "HPM, GC-LB, GC and LB with enhancement tags", "ingested_and_verified"),
    ("EU Ecolabel lubricants", "EU/EEA", "Official open-data API", "https://apps.data.env.service.ec.europa.eu/dataquery/v2/ecolabel/products?group_id__eq=57&limit=1000", 878, "certified product rows", "Public ECAT API; licence, holder, availability and expiry retained", "ingested_and_verified"),
    ("Nordic Swan / EU Ecolabel cross-check", "Nordic product search", "Official CSV export", "https://www.svanen.se/en/product-types/lubricating-grease/?format=Csv", 60, "exported product rows", "All 60 are EU Ecolabel / EU27 Lubricants and reconcile to existing ECAT licences; retained as secondary evidence without duplicate canonical rows", "crosschecked_no_new_canonical_rows"),
    ("USDA BioPreferred", "United States / global suppliers", "Official voluntary product catalog", "https://www.biopreferred.gov/BioPreferred/faces/catalog/Catalog.xhtml", 892, "unique product IDs", "1,387 category occurrences merged by USDA product ID; descriptions excluded from republication", "ingested_and_verified"),
    ("ANP Brazil lubricant registry", "Brazil / imported and national products", "Official weekly open-government CSV", "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/registro-de-oleos-e-graxas-lubrificantes", 12664, "normalized product-grade rows", "14,960 source rows; 8,193 registration numbers; holder, producer, use, SAE/ISO/NLGI, performance, composition and package facts retained", "ingested_and_verified"),
    ("ANP Brazil lubricant monitoring history", "Brazil / sampled market products 2017-2026", "Official open-government XLSX archive", "https://www.gov.br/anp/pt-br/centrais-de-conteudo/publicacoes/boletins-anp/boletins/boletim-de-monitoramento-de-lubrificantes", 11026, "historical sample observations", "Complete 28-workbook machine-readable archive; product, registration, holder, SAE, performance, lot, dates and row-level provenance retained; historical observation is not current-market status", "ingested_and_verified"),
    ("ANP Brazil complete monitoring PDF tables", "Brazil / sampled market products 2024", "Official open-government PDF archive", "https://www.gov.br/anp/pt-br/centrais-de-conteudo/publicacoes/boletins-anp/boletins/boletim-de-monitoramento-de-lubrificantes", 1425, "historical sample observations", "All published rows from two motor-oil PML tables and one transmission-fluid panorama; 693 professional identities; the source reports 190 transmission samples but prints only 181 product rows, so nine rows are not invented", "ingested_and_verified"),
    ("ANP Brazil nonconforming-product PDF appendices", "Brazil / published exceptions 2007-2017", "Official open-government PDF archive", "https://www.gov.br/anp/pt-br/centrais-de-conteudo/publicacoes/boletins-anp/boletins/boletim-de-monitoramento-de-lubrificantes", 4837, "historical exception observations", "Seventy-three reports and 5,612 appendix occurrences; only products reported as nonconforming for registration, labelling or quality are represented, never the complete sampled population; CNPJ, sellers and collection locations are excluded", "ingested_and_verified_explicit_exception_scope"),
    ("Thailand DOEB lubricant registry", "Thailand / registered motor oils", "Official government Open Data Common registry via government CKAN mirror", "https://gdcatalognhic.nha.co.th/dataset/lubricant_data", 5486, "normalized product identities", "March 2024 full snapshot: 6,213 occurrences and 6,210 unique registration numbers; 727 exact holder-product-SAE-performance repeats consolidated with all evidence retained; three colliding numbers remain six separate source-conflict products; lifecycle inferred from published end date", "ingested_and_verified_historical_registry_snapshot"),
    ("Thailand TISI TIS 1040-2541 licences", "Thailand / compulsory two-stroke engine-oil standard", "Official open-government manufacturing-licence registry", "https://appdb.tisi.go.th/tis_dev/p4_license_report/p4license_report.php?data=tis&txt_tis=1040-2541", 10, "certified licence-holder scopes", "Ten manufacturing licences across nine exact holders; CC BY dataset attribution retained; rows are holder-level certification scopes, not marketed brands, grades or SKUs; no SAE/API or current-validity status inferred", "ingested_and_verified_certified_holder_scopes_with_attribution"),
    ("China SAMR 2025 nonconforming automotive fluids", "China / national product-quality inspection", "Official government XLSX inspection notice", "https://www.samr.gov.cn/zw/zfxxgk/fdzdgknr/zljds/art/2026/art_2edd988c928c47ff92cdaa2941bbe013.html", 25, "historical nonconforming product observations", "Twenty-eight relevant rows: nine brake fluids, ten automotive aqueous-urea products and six engine oils with a reported producer are normalized; three counterfeit rows without a producer remain report-only; historical failed-inspection status is explicit and the source workbook is not redistributed", "ingested_and_verified_attributed_nonexpressive_factual_fields_only"),
    ("Shenzhen 2025 complete automotive-fluid inspection", "China / Shenzhen municipal inspection", "Official municipal government complete inspection PDF", "https://www.sz.gov.cn/cn/xxgk/zfxxgj/tzgg/content/mpost_12770607.html", 100, "inspected batch observations", "All 100 automotive rows retained from 246 total rows: 99 conforming and one nonconforming; two repeated/package-variant coolant occurrences merge into 98 identities; no retailer or PDF redistribution and no current-offer inference", "ingested_and_verified_attributed_nonexpressive_factual_fields_only"),
    ("Shenzhen 2020 complete automotive-fluid inspection", "China / Shenzhen municipal inspection", "Official municipal government complete inspection XLSX workbooks", "https://www.sz.gov.cn/cn/xxgk/zfxxgj/tzgg/content/post_8537379.html", 106, "inspected batch observations", "Both complete workbooks retained: 95 conforming and 11 nonconforming observations across 26 engine oils, 25 coolants, 22 brake fluids, 20 urea solutions and 13 fuel additives; four repeated batches yield 102 internal identities and one Audi DOT4/HZY4 identity is reconciled to 2025, adding 101 catalog products; one source-reported counterfeit Shell product remains flagged", "ingested_and_verified_attributed_nonexpressive_factual_fields_only"),
    ("Shenzhen 2019 complete automotive-fluid inspection", "China / Shenzhen municipal inspection", "Official municipal government complete inspection XLS workbooks", "https://www.sz.gov.cn/cn/xxgk/zfxxgj/scjg/cpzljy/content/post_6601774.html", 60, "inspected batch observations", "All 60 observations retained: 20 urea solutions, 20 fuel additives and 20 brake/clutch fluids; 51 no-problem-found and nine nonconforming batches; ten observations reconcile to nine existing identities, one JMC repeat is merged and 49 products are added; AUS30 remains atypical and flagged; no retailer/source-workbook redistribution or current-offer inference", "ingested_and_verified_attributed_nonexpressive_factual_fields_only"),
    ("China SAMR 2024 nonconforming gasoline detergent additives", "China / national product-quality inspection", "Official government XLSX inspection notice", "https://www.samr.gov.cn/zw/zfxxgk/fdzdgknr/zljds/art/2025/art_d75bb5a15c794893bca6cf8baf9f5155.html", 23, "historical nonconforming product observations", "Twenty-three exact nominal producer + product + package identities; nine retest failures; source workbook and retailer/lab fields not redistributed", "ingested_and_verified_attributed_nonexpressive_factual_fields_only"),
    ("Shenzhen 2021 nonconforming automotive fluids", "China / Shenzhen municipal inspection", "Official municipal government XLSX inspection notice", "https://www.sz.gov.cn/cn/xxgk/zfxxgj/scjg/cpzljy/content/mpost_9934070.html", 12, "historical nonconforming product observations", "One diesel row excluded; six engine oils, three coolants, two washer fluids and one gasoline detergent additive retained; one later SAMR identity linked without duplication", "ingested_and_verified_attributed_nonexpressive_factual_fields_only"),
    ("China SAMR 2023 nonconforming automotive fluids", "China / national product-quality inspection", "Official SAMR XLSX mirrored by local government", "https://www.shandan.gov.cn/zfxxgk/fdzdgknr/ssjygkhjdjc_5883/202310/t20231020_1128402.html", 126, "historical nonconforming product observations", "136 relevant rows across six fluid types; 126 normalized, ten explicit suspected-counterfeit rows report-only; one exact identity linked to its 2025 inspection occurrence", "ingested_and_verified_attributed_nonexpressive_factual_fields_only"),
    ("Beijing 2018 automotive fluids — first release", "China / Beijing municipal inspection", "Official municipal government complete inspection XLS", "https://scjgj.beijing.gov.cn/zwxx/gs/cpzlgs/201909/t20190904_267303.html", 147, "inspected batch observations", "All relevant rows retained: nine gasoline detergent additives, 22 urea solutions, 76 engine oils, 35 coolants and five brake fluids; current official attachment is a pinned later portal reissue of the 2018 report", "ingested_and_verified_attributed_nonexpressive_factual_fields_only"),
    ("Beijing 2018 automotive fluids — second release", "China / Beijing municipal inspection", "Official municipal government complete inspection HTML", "https://scjgj.beijing.gov.cn/zwxx/gs/cpzlgs/201909/t20190904_267220.html", 147, "inspected batch observations", "All relevant rows retained: nine gasoline detergent additives, 47 urea solutions, 86 engine oils and five coolants; one missing source date cell is preserved as missing rather than shifted", "ingested_and_verified_attributed_nonexpressive_factual_fields_only"),
    ("Shanghai 2023 industrial lubricants — first batch", "China / Shanghai municipal inspection", "Official municipal government complete inspection HTML", "https://scjgj.sh.gov.cn/923/20230821/2c984a728a15e02c018a17a844d623f4.html", 64, "inspected batch observations", "All 64 rows retained: 60 conforming and four nonconforming; source product/model fields preserve explicit SAE, API GL, ISO VG and Chinese L-classes", "ingested_and_verified_attributed_nonexpressive_factual_fields_only"),
    ("Shanghai 2023 industrial lubricants — second batch", "China / Shanghai municipal inspection", "Official municipal government complete inspection HTML", "https://scjgj.sh.gov.cn/923/20231121/2c984a728bdfc867018befd976ca2dbb.html", 35, "inspected batch observations", "All 35 rows retained: 29 conforming and six nonconforming; historical batch outcomes are not current-offer or blanket-approval claims", "ingested_and_verified_attributed_nonexpressive_factual_fields_only"),
    ("Shanghai 2024 industrial lubricants", "China / Shanghai municipal inspection", "Official municipal government complete inspection HTML", "https://scjgj.sh.gov.cn/923/20240924/2c984a7292079f74019222bb71ac71e7.html", 131, "inspected batch observations", "All 131 conforming rows retained with producer, brand, product, model/specification and batch provenance", "ingested_and_verified_attributed_nonexpressive_factual_fields_only"),
    ("Shanghai 2025 engine oils", "China / Shanghai municipal inspection", "Official municipal government complete inspection HTML", "https://scjgj.sh.gov.cn/923/20250728/2c984a72984f47f201985041e2560dfa.html", 30, "inspected batch observations", "All 30 conforming rows retained with SAE and API; source Cl-4 is transparently normalized to valid API CI-4 with a quality flag", "ingested_and_verified_attributed_nonexpressive_factual_fields_only"),
    ("Shanghai 2025 industrial lubricants", "China / Shanghai municipal inspection", "Official municipal government complete inspection HTML", "https://scjgj.sh.gov.cn/923/20251111/2c984a729a0b6239019a721b444c52ff.html", 130, "inspected batch observations", "All 130 rows retained: 126 conforming and four nonconforming; sampled retailers and platforms excluded", "ingested_and_verified_attributed_nonexpressive_factual_fields_only"),
    ("Indonesia NPT lubricant registry", "Indonesia / registered products", "Official public-government registry PDF", "https://migas.esdm.go.id/daftar-umum-pelumas", 12626, "published product rows", "2021-2025 list: 12,575 rows with NPT, 51 source placeholders; expiry lifecycle is computed and labelled as an inference", "ingested_and_verified"),
    ("Blue Angel DE-UZ 178", "Germany / certified products", "Official ecolabel product registry with XLSX export", "https://www.blauer-engel.de/de/produktwelt/schmierstoffe-und-hydraulikfluessigkeiten", 148, "normalized certified products", "149 export rows and product cards; one exact duplicate identity merged; 159 category occurrences across seven official lubricant categories; contact and marketing fields excluded", "ingested_and_verified"),
    ("Austrian Ecolabel UZ 14", "Austria / international licensees", "Official government ecolabel XLSX and product cards", "https://www.umweltzeichen.at/de/produkte/garten-gr%C3%BCnraum", 11, "current certified product identities", "Five licensees and 11 exact product cards; ten attach as independent evidence to existing identities and one is new; factual fields only; attribution and noncommercial-use restriction recorded", "ingested_and_verified_noncommercial_use"),
    ("Korea Eco-Label EL611", "Republic of Korea / certified products", "Official open-government ecolabel CSV", "https://www.data.go.kr/data/15043624/fileData.do", 20, "normalized certified products", "240,695 file rows observed versus 99,602 in portal metadata; exact EL611 filter yields 21 lubricant rows and 20 product identities; unrestricted use; business and location identifiers excluded", "ingested_and_verified"),
    ("Korea Eco-Label EL509", "Republic of Korea / certified products", "Official open-government ecolabel CSV", "https://www.data.go.kr/data/15043624/fileData.do", 9, "normalized certified technical fluids", "Exact EL509 filter yields 11 vehicle glass washer fluid rows and nine product identities after package-model merging; unrestricted use; business and location identifiers excluded", "ingested_and_verified"),
    ("Green Choice Philippines GCP 2008032", "Philippines / historical certification", "National ecolabel public licence checker", "https://pcepsdi.org.ph/check-gcp-seal/", 3, "expired named engine-oil licences", "All three exact automotive-engine-oil rows occur only in the official Expired table; source typo SW-40 retained and flagged, not corrected by guess", "ingested_and_verified_historical_only"),
    ("UAE MOIAT Product Conformity", "United Arab Emirates / international certified products", "Official open-government certification registry", "https://moiat.gov.ae/en/open-data/product-conformity-data", 1840, "normalized product/model identities", "131 listing pages; 1,236 certificates; 3,176 product-certificate occurrences; explicit package suffixes and certificate renewals merged; 111 products active at snapshot; open-data page permits unrestricted reuse", "ingested_and_verified"),
    ("EAEU conformity-document register", "EAEU member states / imported and domestic products", "Official open-government OData/REST conformity register", "https://tech.eaeunion.org/tech/registers/35-1", 38444, "normalized manufacturer/holder + reported designation + family identities", "81,076 unique documents across 17 exact ten-digit TN VED code slices; 51,768 candidate occurrences; 13,324 repeat certificate occurrences merged; 2,943 explicit trademarks and 35,501 clearly flagged manufacturer/holder fallbacks; register evidence is not current-market proof", "ingested_and_verified_conservative_product_evidence"),
    ("US EPA Safer Choice", "United States", "Official open-government bulk CSV/API", "https://data.epa.gov/efservice/t_safer_choice_and_design_for_the_environment/CSV", 2, "normalized explicitly named lubricant products", "12 UPC/GTIN/MPN occurrences in 4,786 source rows merged to two medical-instrument lubricants; degreasers and grease-trap cleaners excluded", "ingested_and_verified_curated_scope"),
    ("US EPA ChemExpo / CPDat 4.1", "United States / historical and current public-source records", "Official government CC0 product database and public PUC API", "https://comptox.epa.gov/chemexpo/", 5915, "normalized lubricant and technical-fluid product identities", "10,342 product-ID occurrences reviewed across 19 relevant or adjacent PUCs; 7,450 retained occurrences normalized to 5,915 identities after package and repeat-record merging; the added mold-release PUC retains 233 of 323 occurrences after strict audit; lifecycle is never inferred", "ingested_and_verified_curated_scope_historical_or_current_unverified"),
    ("KEBS S-Mark", "Kenya / locally manufactured certified products", "Official government product-certification directory", "https://www.kebs.org/products-with-smarks/", 750, "normalized lubricant and technical-fluid products", "25 search slices; 4,276 visible cards; 2,897 unique permits observed; strict scope retained 775 permits and merged 25 renewals/duplicates; factual certification fields only, standard body text excluded", "ingested_and_verified_curated_scope"),
    ("UNBS certified products", "Uganda / locally manufactured certified products", "Official government product-certification directory", "https://cims.unbs.go.ug/api/website/", 46, "normalized lubricant and brake-fluid products", "13,091 public certification rows; 47 exact-scope permit occurrences; one historical renewal merged; district/location and standards body text excluded", "ingested_and_verified_curated_scope"),
    ("TBS certified companies", "Tanzania / locally manufactured certified products", "Official government product-certification directory", "https://www.tbs.go.tz/index.php/companies", 183, "normalized lubricant, coolant and brake-fluid products", "2,642 public certification rows; 70 exact-scope certificates expose 184 marketed designations; one repeated occurrence merged; locations and standards body text excluded", "ingested_and_verified_curated_scope"),
    ("SON MANCAP Chemical Sector", "Nigeria / locally manufactured certified products", "Official mandatory product-certification PDF", "https://son.gov.ng/wp-content/uploads/2026/07/CHEMICAL-PRODUCTS-SECTOR_compressed.pdf", 608, "normalized lubricant, grease, coolant and technical-fluid products", "233 pages and 2,011 consecutively numbered certification rows; 286 scope certificates expose 613 marketed designations; five exact notation/repeated-row duplicates merged; addresses, state and mark artwork excluded", "ingested_and_verified_curated_scope"),
    ("RSB S-Mark", "Rwanda / locally manufactured certified products", "Official government product-certification directory", "https://www.rsb.gov.rw/certifications/directories/products-with-s-marks-1", 9, "normalized currently valid lubricant products", "1,843 public directory rows numbered through 1,846; exact product names and standards retain eight engine oils plus one food-grade lubricant; location and contacts excluded", "ingested_and_verified_curated_scope"),
    ("PSQCA CM licence verification", "Pakistan / certified manufacturers", "Official government product-certification licence directory", "https://icq.psqca.com.pk/e_services/t_cmverify.aspx", 14, "certified engine-oil brand scopes", "Two exact PS 343 engine-oil filters expose 14 CM licences: one valid and 13 expired at snapshot; these are brand-level scopes, not individual SAE/API grades", "ingested_and_verified_conservative_brand_scope"),
    ("Philippine BPS PS licensees", "Philippines / local and foreign PS licensees", "Official government live certification spreadsheet", "https://bps.dti.gov.ph/product-certification/certified-products", 89, "brake-fluid licence + label + DOT scopes", "3,558 PS rows as of 2026-05-31; 13 exact motor-vehicle-brake-fluid licences expand to 89 grade scopes using audited source mappings; source conflicts remain flagged", "ingested_and_verified_conservative_certification_scope"),
    ("Philippine BPS ICC certificate holders", "Philippines / imported certified products", "Official government live import-certification spreadsheet", "https://bps.dti.gov.ph/product-certification/certified-products", 34, "normalized brake-fluid holder + label + class identities", "19,461 ICC rows as of 2026-04-30; 114 exact brake-fluid source rows and 129 grade occurrences normalize to 34 identities after repeated sticker-range merging; source-data anomalies retained", "ingested_and_verified_conservative_certificate_evidence"),
    ("BIS product-certification licences", "India / certified manufacturers", "Official interactive government certification directory", "https://www.manakonline.in/MANAK/ApplicationLicenceRelatedrpt", None, None, "Schema exposes licence, manufacturer, IS, variety and brands, but report generation is CAPTCHA-protected; no bypass attempted", "official_feed_or_written_access_required"),
    ("Pakistan State Oil", "Pakistan / current domestic catalog", "Official state-owned manufacturer product pages and PDS", "https://psopk.com/en/lubricants", 124, "normalized current series-grade rows", "Forty-three current series pages and linked PDS documents; two webpage-only grades explicitly marked; one exact PSO DEO 8000 SAE 15W-40 identity reconciled to Mercedes DTFR evidence; factual fields only under noncommercial informational-use terms with attribution", "ingested_and_verified_noncommercial_use"),
    ("Pertamina Lubricants", "Indonesia / current domestic and automotive catalog", "Official state-owned manufacturer catalog API, webpages and linked PDS", "https://www.pertaminalubricants.com/industry/industry_produk", 250, "normalized current product-grade rows", "104 industrial cards/PDS plus 22 automotive cards yield 252 occurrences and 250 normalized rows; PDS tables govern grades; one mismatched Rusguard PDS is isolated; attributed non-expressive factual fields only", "ingested_and_verified_current_factual_fields_only"),
    ("BPCL MAK Lubricants", "India / international markets", "Official manufacturer product catalog", "https://www.bharatpetroleum.in/our-businesses/mak-lubricants/about-mak-lubricants", 400, "publicly stated minimum grades", "Official page reports 400+ grades; terms require prior written permission for copying or republication, so no product rows imported", "written_permission_required"),
    ("Japan Eco Mark Category 110", "Japan / certified products", "Official ecolabel product search", "https://www.ecomark.jp/search/op_item_list.php?rkw=1&ruigata=1102", 124, "current certified search entries", "Live count observed 2026-07-21; site policy restricts republication and processed use, so only count and source link retained pending written permission", "permission_required"),
    ("DLA QPD FSC 9150", "United States / international qualified sources", "Official government qualified-products database", "https://qpldocs.dla.mil/search/default.aspx", 431, "normalized qualified products", "56 active QPLs; 455 product occurrences; GREEN/YELLOW/RED, SAM and Stop Ship retained separately; plant-only rows and personal/contact fields excluded", "ingested_and_verified"),
    ("DLA QPD FSC 6850 lubricant scope", "United States / international qualified sources", "Official government qualified-products database, curated professional subset", "https://qpldocs.dla.mil/search/default.aspx", 25, "normalized qualified products", "Six of 24 active FSC 6850 QPLs retained because the governing title explicitly establishes oil, silicone compound, cleaning-lubricating compound or fuel-lubricity function; pure cleaners and unrelated chemicals excluded", "ingested_and_verified_curated_scope"),
    ("ZF TE-ML", "Global OEM approvals", "Official approved-lubricant ZIP/PDF registry", "https://aftermarket.zf.com/lubricants/en/2026-07-01_en.zip", 1498, "unique approval numbers", "4,919 approval occurrences across 28 TE-ML lists dated 2026-07-01", "ingested_and_verified"),
    ("Allison TES approved fluids", "Global OEM approvals", "Official approved-fluid PDF registry", "https://allisontransmission.com/en-gb/aftermarket---channel/parts---service/allison-approved-fluids", 104, "approved products", "Six current TES lists; 119 approval-number occurrences and 117 unique approval numbers", "ingested_and_verified"),
    ("Driventic DIWA approved oils", "Global OEM approvals", "Official approved-oil PDF registry", "https://www.driventic.com/products/bus/diwa-automatic-transmission", 226, "approved products", "Four currently published highest-version lists for 60,000 to 240,000 km oil-change intervals; source list dates retained", "ingested_and_verified"),
    ("Mercedes-Benz Trucks DTFR", "Global OEM approvals", "Official operating-fluids approval API", "https://bevo.mercedes-benz-trucks.com/", 1892, "unique DTFR product IDs", "2,102 approval occurrences across 63 product sheets; historical-only approvals retain lifecycle status", "ingested_and_verified"),
    ("Mercedes-Benz BeVo", "Global OEM approvals", "Official operating-fluids approval API", "https://operatingfluids.mercedes-benz.com/", 1913, "normalized approved products", "2,461 approval occurrences across 92 product sheets; 158 products cross-matched to Trucks DTFR", "ingested_and_verified"),
    ("Volvo Genuine Fluids", "Volvo CE Asia / Volvo Trucks US-CA", "Official manufacturer product catalog", "https://www.volvoce.com/asia/en-as/parts/maintenance-parts/lubricants/", 32, "specific product-grade rows", "Five official catalog pages; ungraded VDS series excluded from product count", "ingested_and_verified"),
    ("Volvo Group WebSDS change archive", "Volvo Group / Volvo Cars / Renault Trucks", "Official SDS change-list archive", "https://websds.volvo.com/websds/sdsNews", 144, "conservative product/part identities", "50 documents, 833 table rows, 537 relevant occurrences and 394 unique part numbers; current market availability explicitly unverified", "ingested_and_verified_attributed_factual_fields"),
    ("Parker-Denison fluid ratings", "Global", "Official current OEM hydraulic-fluid rating PDF", "https://discover.parker.com/hydraulic-fluid-evaluation-process", 217, "manufacturer-product rating rows", "Reviewed 2026-04-14; 104 manufacturers; ISO VG 32/46/68, HM/HV, ashless/zinc-free, HF classes and validity retained; 11 expired and one malformed validity value explicitly separated", "ingested_and_verified_attributed_factual_fields"),
    ("Bosch Rexroth RDE 90245", "Global", "Official current OEM hydraulic-fluid rating PDF", "https://www.boschrexroth.com/media/89377363-ace1-4912-83b7-3937603c6b73", 217, "positive rating rows observed", "Current 2026-06-19 document reviewed in full; exact ISO VG, fluid category and validity fields are available, but the document and legal notice reserve reproduction, editing and distribution rights; no normalized rows imported", "written_permission_or_official_feed_required"),
    ("Mack Genuine Fluids", "Bahamas English / North American technical evidence", "Official manufacturer product catalog and product sheets", "https://bahamas.macktrucks.com/parts-and-services/parts/mack-parts/material-safety-data-sheets", 15, "current product-grade rows", "15 products, 32 package offers and 38 unique regional part numbers; two incorrect SDS-link targets and unusual source formatting are explicitly flagged", "ingested_and_verified_attributed_factual_fields"),
    ("Mack Approved Oils 2014", "Global historical service bulletin", "Official historical OEM approval PDF", "https://sv.macktrucks.com/media/files/body-builder/pv776-89149448.pdf", 803, "normalized historical product-grade identities", "806 approval occurrences; 805 section-level rows; one duplicated source row and two cross-section/notation identities merged; lifecycle is historical and current status is unverified", "ingested_and_verified_historical_oem_approvals"),
    ("Valvoline–Cummins Europe 2022", "Europe / historical corporate catalog", "Official Cummins-hosted manufacturer/OEM catalog PDF", "https://www.cummins.com/sites/default/files/Europe/2204606-valvoline-eu-cummins-product-catalog-apr22.pdf", 166, "historical product cards", "166 products, 510 package/article assignments and 502 unique article numbers; eight cross-product article collisions retained and flagged; current status unverified", "ingested_and_verified_historical_corporate_catalog"),
    ("Cummins current registered oil lists", "Global / QuickServe", "Official current OEM registration registry", "https://quickserve.cummins.com/info/qsol/news/oil_registration.html", None, None, "Product tables require an authenticated QuickServe plan; no login bypass attempted and no current row claimed", "authorized_quickserve_access_required"),
    ("Repsol Lubricants", "Global / market-specific", "Official manufacturer product catalog", "https://lubricants.repsol.com/es/productos/", None, None, "Legal notice restricts reproduction and transformation; no rows imported pending permission or licensed feed", "written_permission_or_official_feed_required"),
    ("Eaton Approved Lubricants TCMT0020", "Global / regional availability", "Official OEM approved-lubricant PDF", "https://www.eaton.com/content/dam/eaton/products/transmissions/lubricants/eaton-lubricant-suppliers-brochure-tcmt0020.pdf", None, None, "Site terms restrict downloads to personal non-commercial use and PDF copying permission is limited to complete printed copies; no normalized rows imported", "written_permission_or_official_feed_required"),
    ("Mexico CONUEE certified products", "Mexico", "Official open-government CSV", "https://www.datos.gob.mx/dataset/buscador_productos_certificados", 0, "lubricant-scope rows", "March 2026 CSV has 7,835 energy-efficiency product rows and zero strict lubricant/coolant/technical-fluid matches", "reviewed_zero_relevant_rows"),
    ("Egypt EOS Quality Mark products", "Egypt / current valid licences", "Official government product-certification directory", "https://www.eos.org.eg/ar/products?mark_type=1", 0, "lubricant-scope rows", "All 143 visible certificate-holder pages and 238 current product rows were reviewed; two automated candidates were limestone-cement false positives and no lubricant, grease, coolant or technical-fluid product remained", "reviewed_zero_relevant_rows"),
    ("Ceypetco lubricants", "Sri Lanka", "Official state-owned supplier catalog + TDS", "https://ceypetco.gov.lk/ceypetco-lubricants/", 47, "normalized product-grade/color rows", "23 official product lines and 22 current TDS files; two source-document conflicts preserved as quality flags; factual fields only", "ingested_and_verified"),
    ("MAN current service products", "MAN trucks / global English document", "Official current OEM service recommendation", "https://public.man.eu/media/service/asp/media/en/927247.pdf", 32, "named products", "April 2026 edition; 33 recommendation occurrences; standards and ungraded series excluded", "ingested_and_verified"),
    ("API EOLCS", "Global", "Official licensed engine-oil directory", "https://engineoil.api.org/Directory/EolcsProductResults?accountId=-1", 35174, "licensed product rows", "Live 2026-07-21 count: 35,174 products from 883 companies; API terms prohibit bulk copying/republication, so only aggregate evidence is retained", "written_permission_or_official_feed_required"),
    ("NSF White Book", "Global", "Official nonfood compounds registry", "https://info.nsf.org/USDA/psnclistings.asp", None, None, "Food-grade lubricants and related compounds; public search available, bulk rights and feed must be confirmed", "terms_and_feed_review_required"),
    ("Flender T7300", "Global OEM approvals", "Official approved-lubricants pages", "https://www.flender.com/en/approvedlubricants", None, None, "Current approval tables are public, but Flender Terms of Use prohibit copying, reproducing or exploiting site content without written consent", "written_permission_required"),
    ("TotalEnergies", "Global", "Product catalog", "https://lubricants.catalog.totalenergies.com/corporate/en_UK", 1246, "products", "Count observed 2026-07-20; GTCU 4.3 prohibits substantial database extraction/reuse", "written_permission_required"),
    ("Shell", "Global / market-specific", "EPC product catalog", "https://www.epc.shell.com/?lang=eng", None, None, "TDS/SDS by market; copying is restricted by site terms", "permission_or_permitted_access_required"),
    ("Mobil", "Global / market-specific", "Industrial product search", "https://www.mobil.com/en/lubricants/for-businesses/industrial/lubricants/search", None, None, "Terms prohibit bots; permitted feed or written permission required", "permission_or_licensed_feed_required"),
    ("FUCHS", "India", "Official embedded product finder", "https://www.fuchs.com/in/en/products/service-links/product-finder/", 1007, "normalized product-grade rows", "1,115 embedded rows; 94 series and 6 equipment rows excluded; 8 duplicate occurrences merged; factual fields only, descriptions omitted", "ingested_and_verified_factual_fields_only"),
    ("FUCHS", "United States", "Official embedded product finder", "https://www.fuchs.com/us/en/products/service-links/product-finder/", 623, "normalized product-grade rows", "686 embedded rows; 60 series excluded; 3 duplicate occurrences merged; factual fields only; exact India overlaps reconciled by name and professional family", "ingested_and_verified_factual_fields_only"),
    ("FUCHS", "Germany", "Official embedded product finder", "https://www.fuchs.com/de/en/products/service-links/product-finder/", 1464, "normalized product-grade rows", "1,464 concrete catalog cards; no series or duplicate occurrences; factual fields only; cross-market identity reconciled by exact name and professional family", "ingested_and_verified_factual_fields_only"),
    ("FUCHS", "Poland", "Official embedded product finder", "https://www.fuchs.com/pl/en/products/service-links/product-finder/", 690, "normalized product-grade rows", "776 embedded rows; 81 localized series/group rows excluded; 5 duplicate occurrences merged; Polish taxonomy normalized to professional families; factual fields only", "ingested_and_verified_factual_fields_only"),
    ("FUCHS", "Italy", "Official embedded product finder", "https://www.fuchs.com/it/en/products/service-links/product-finder/", 1007, "normalized product-grade rows", "1,174 embedded rows; 84 series and 4 equipment rows excluded; 79 duplicate occurrences merged; factual fields only", "ingested_and_verified_factual_fields_only"),
    ("FUCHS", "Sweden", "Official embedded product finder", "https://www.fuchs.com/se/en/products/service-links/product-finder/", 675, "normalized product-grade rows", "675 concrete cards; no series, equipment or duplicate occurrences; factual fields only", "ingested_and_verified_factual_fields_only"),
    ("FUCHS", "Spain", "Official embedded product finder", "https://www.fuchs.com/es/en/products/service-links/product-finder/", 938, "normalized product-grade rows", "1,017 embedded rows; 69 series, 6 equipment rows and 1 test placeholder excluded; 3 duplicate occurrences merged; factual fields only", "ingested_and_verified_factual_fields_only"),
    ("FUCHS", "France", "Official embedded product finder", "https://www.fuchs.com/fr/en/products/service-links/product-finder/", 705, "normalized product-grade rows", "765 embedded rows; 42 series and 1 equipment row excluded; 17 duplicate occurrences merged; factual fields only", "ingested_and_verified_factual_fields_only"),
    ("FUCHS", "Turkey", "Official embedded product finder", "https://www.fuchs.com/tr/en/products/service-links/product-finder/", 583, "normalized product-grade rows", "632 embedded rows; 44 series and 2 equipment rows excluded; 3 duplicate occurrences merged; no general website imprint found, conservative factual-only publication", "ingested_and_verified_conservative_factual_fields_only"),
    ("FUCHS", "Canada", "Official embedded product finder", "https://www.fuchs.com/ca/en/products/service-links/product-finder/", 289, "normalized product-grade rows", "323 embedded rows; 34 series excluded; no equipment or duplicate occurrences; factual fields only", "ingested_and_verified_factual_fields_only"),
    ("FUCHS", "China", "Official embedded product finder", "https://www.fuchs.com/cn/en/products/service-links/product-finder/", 278, "normalized product-grade rows", "281 embedded rows; 2 series excluded; 1 duplicate occurrence merged; informational factual fields only under official imprint", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "Czech Republic", "Official embedded product finder", "https://www.fuchs.com/cz/en/products/service-links/product-finder/", 1146, "normalized product-grade rows", "1,253 embedded rows; 98 series and 6 equipment rows excluded; 3 duplicate occurrences merged; factual fields only", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "Mexico", "Official embedded product finder", "https://www.fuchs.com/mx/en/products/service-links/product-finder/", 314, "normalized product-grade rows", "364 embedded rows; 50 series excluded; factual fields only", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "South Africa", "Official embedded product finder", "https://www.fuchs.com/za/en/products/service-links/product-finder/", 756, "normalized product-grade rows", "864 embedded rows; 94 series and 6 equipment rows excluded; 8 duplicate occurrences merged; factual fields only", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "Brazil", "Official embedded product finder", "https://www.fuchs.com/br/en/products/service-links/product-finder/", 182, "normalized product-grade rows", "213 embedded rows; 30 series excluded; one duplicate occurrence merged; informational factual fields only under official imprint", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "Norway", "Official embedded product finder", "https://www.fuchs.com/no/en/products/service-links/product-finder/", 649, "normalized product-grade rows", "650 embedded rows; one series excluded; no duplicate occurrences; informational factual fields only under official imprint", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "Hungary", "Official embedded product finder", "https://www.fuchs.com/hu/en/products/service-links/product-finder/", 506, "normalized product-grade rows", "544 embedded rows; 37 series excluded; one duplicate occurrence merged; informational factual fields only under official imprint", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "Denmark", "Official embedded product finder", "https://www.fuchs.com/dk/en/products/service-links/product-finder/", 640, "normalized product-grade rows", "641 embedded rows; one series excluded; informational factual fields only", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "Finland", "Official embedded product finder", "https://www.fuchs.com/fi/en/products/service-links/product-finder/", 599, "normalized product-grade rows", "639 embedded rows; 38 series excluded; two duplicate occurrences merged", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "Portugal", "Official embedded product finder", "https://www.fuchs.com/pt/en/products/service-links/product-finder/", 484, "normalized product-grade rows", "529 embedded rows; 42 series and two equipment rows excluded; one duplicate merged", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "Romania", "Official embedded product finder", "https://www.fuchs.com/ro/en/products/service-links/product-finder/", 691, "normalized product-grade rows", "794 embedded rows; 91 series and one equipment row excluded; 11 duplicates merged", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "Austria", "Official embedded product finder", "https://www.fuchs.com/at/en/products/service-links/product-finder/", 952, "normalized product-grade rows", "1,057 embedded rows; 94 series and six equipment rows excluded; five duplicates merged", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "Greece", "Official embedded product finder", "https://www.fuchs.com/gr/en/products/service-links/product-finder/", 966, "normalized product-grade rows", "1,074 embedded rows; 97 series and six equipment rows excluded; five duplicates merged", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "Switzerland", "Official embedded product finder with Germany taxonomy reconciliation", "https://www.fuchs.com/ch/en/products/service-links/product-finder/", 1464, "normalized product-grade rows", "1,453 exact Germany-name matches reconcile 203 family differences and all 234 fallback rows; 11 unique Swiss products retain source classification", "ingested_and_verified_cross_market_taxonomy_reconciled"),
    ("FUCHS", "Republic of Korea", "Official embedded product finder", "https://www.fuchs.com/kr/en/products/service-links/product-finder/", 221, "normalized product-grade rows", "249 embedded rows; 28 series excluded; informational factual fields only", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "United Arab Emirates", "Official embedded product finder", "https://www.fuchs.com/ae/en/products/service-links/product-finder/", 965, "normalized product-grade rows", "1,073 embedded rows; 97 series and six equipment rows excluded; five duplicate occurrences merged", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "Argentina", "Official embedded product finder", "https://www.fuchs.com/ar/en/products/service-links/product-finder/", 5, "normalized product-grade rows", "35 embedded rows; 30 series excluded; informational factual fields only", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "Chile", "Official embedded product finder", "https://www.fuchs.com/cl/en/products/service-links/product-finder/", 496, "normalized product-grade rows", "549 embedded rows; 49 series and four equipment rows excluded", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "Ukraine", "Official embedded product finder", "https://www.fuchs.com/ua/en/products/service-links/product-finder/", 842, "normalized product-grade rows", "918 embedded rows; 65 series, six equipment rows and one blank placeholder excluded; four duplicate occurrences merged", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "Slovakia", "Official embedded product finder", "https://www.fuchs.com/sk/en/products/service-links/product-finder/", 966, "normalized product-grade rows", "1,074 embedded rows; 97 series and six equipment rows excluded; five duplicate occurrences merged", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "Slovenia", "Official embedded product finder", "https://www.fuchs.com/si/en/products/service-links/product-finder/", 1, "normalized product-grade row", "One embedded concrete product card; informational factual fields only", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "Croatia", "Official embedded product finder", "https://www.fuchs.com/hr/en/products/service-links/product-finder/", 975, "normalized product-grade rows", "1,082 embedded rows; 96 series and six equipment rows excluded; five duplicate occurrences merged", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS", "Belgium / Benelux", "Official embedded product finder", "https://www.fuchs.com/be/en/products/service-links/product-finder/", 591, "normalized product-grade rows observed", "673 embedded rows; official imprint prohibits copying and republication except personal non-commercial downloads", "written_permission_required"),
    ("ZABS certified products", "Zambia", "Official government certification register", "https://www.zabs.org.zm/certification", 85, "product-certification holder records", "Public register has 181 total certification records; product tabs expose 85 holder-standard records, including Mount Meru Lubricants and two Willowton Oil records, but no marketed product/SKU names", "reviewed_no_product_sku_rows"),
    ("BOBS product certification register", "Botswana", "Official government certification register", "https://bobstandards.bw/product-certification-register-2/", 120, "certification records", "All 120 public rows reviewed at the snapshot; no lubricant, grease, coolant or technical-fluid product scope found", "reviewed_zero_relevant_product_rows"),
    ("SABS certified clients", "South Africa", "Official government certification search", "https://www.sabs.co.za/sabs-certified-clients", None, None, "Searchable system and product-client register exposes company, permit, specification and scope; lubricant-related queries returned organizations and adjacent products, not marketed lubricant SKU names", "reviewed_no_product_sku_rows"),
    ("BSTI CM licence lists", "Bangladesh", "Official regional certification PDF lists", "https://bsti.gov.bd/site/page/fae2ce93-b2cd-49c4-af5b-d2e9733d6211/List-of-companies-licensed-from-BSTI", 9, "generic lubricant licence-class rows", "Twenty-one PDFs reviewed; relevant rows expose holder, licence and generic standard scope, but no marketed brand, grade or product designation", "reviewed_no_product_sku_rows"),
    ("Taiwan MOENV ecolabel products", "Taiwan", "Official open-government API", "https://data.moenv.gov.tw/dataset/detail/GP_P_02", 0, "relevant product rows", "All 26,488 records reviewed; 32 apparent oil hits were digital-copying ink false positives", "reviewed_zero_relevant_product_rows"),
    ("Malaysia SIRIM certified products", "Malaysia", "Official certified-product directory", "https://www.malaysiancertified.com.my/", None, None, "Current product search requires member authentication; no access control bypassed", "authorized_data_access_required"),
    ("Singapore Green Labelling Scheme", "Singapore / international licensees", "Official Type I ecolabel directory", "https://sgls.sec.org.sg/product-categories/", 0, "lubricant product standards", "Current 58 standards across nine top-level categories contain no lubricant, grease, coolant or automotive-fluid standard", "reviewed_zero_relevant_product_rows"),
    ("Thailand Green Label TGL-20", "Thailand / certified products", "Official Type I ecolabel monthly archives", "https://greenlabel.tei.or.th/en/list-of-products-certified-with-green-labels/", 0, "certified lubricant product rows", "TGL-20 lubricant criteria exist, but the June 2026 list and year-end 2017-2025 official snapshots contain only criteria-index mentions and no lubricant product section", "reviewed_zero_relevant_product_rows"),
    ("Eco Choice Aotearoa", "New Zealand / certified products", "Official Type I ecolabel product directory", "https://environmentalchoice.org.nz/tools-resources/products/", 0, "lubricant product standards", "Current 816-product directory and published standards contain no lubricant, grease, coolant or automotive-fluid scope", "reviewed_zero_relevant_product_rows"),
    ("GECA", "Australia / certified products", "Official Type I ecolabel product directory", "https://www.geca.eco/products", 0, "lubricant product standards", "Current 2,000-plus-product directory and standards contain no lubricant, grease, coolant or automotive-fluid scope", "reviewed_zero_relevant_product_rows"),
    ("Hong Kong Green Label Scheme", "Hong Kong / certified products", "Official Type I ecolabel product directory", "https://www.greencouncil.org/hkgls4", 0, "lubricant product categories", "Current certified categories contain no lubricant, grease, coolant or automotive-fluid scope", "reviewed_zero_relevant_product_rows"),
    ("SASO Saudi Quality Mark", "Saudi Arabia / current certified products", "Official government product-certification directory", "https://www.saso.gov.sa/en/qualitysign/pages/companies-products.aspx", 0, "lubricant-scope product rows", "All four Chemical-product companies (95 product cards) and both Mechanical-product companies (69 product cards) were reviewed through the public WebForms workflow; paints, butane, household chemicals, commercial cooking equipment and cable systems only", "reviewed_zero_relevant_product_rows"),
    ("Scania genuine engine oils", "Middle East / Gulf Region", "Official manufacturer regional product page", "https://www.scania.com/ae/en/home/services/repair-and-maintenance/scania-oil.html", 4, "current product-grade rows", "Four named engine oils; two explicit SAE grades, one explicit ACEA class and four temperature ranges; LDF-4 SAE deliberately not inferred; Creative Commons 3.0 noncommercial use with attribution", "ingested_and_verified_noncommercial_use"),
    ("MBS certified and pre-certified products", "Malawi / May 2023 historical", "Official government certification directory recovered from Web Archive", "https://mbsmw.org/wp-content/uploads/2023/06/DIRECTORY-OF-CERTIFIED-AND-PRE-CERTIFIED-PRODUCTS-AND-SERVICES-MAY-2023_compressed12.pdf", 0, "relevant product rows", "All 154 pages and 928 entries reviewed; oil hits are edible/hair/release products, with no professional lubricant or technical-fluid row", "reviewed_zero_relevant_product_rows"),
    ("SAZ certified products", "Zimbabwe / regional current lists", "Official product-certification directories", "https://www.saz.org.zw/certify-your-product/", 0, "relevant product rows", "Harare, Bulawayo and Mutare lists reviewed in full; no marketed lubricant or technical-fluid row", "reviewed_zero_relevant_product_rows"),
    ("MSB Mauricert licences", "Mauritius / as at 2025-12-31", "Official government product-certification directory", "https://msb.intnet.mu/Documents/Certification-Schemes/MSB%20Certification%20Mark/Mauricert%20Licences%20as%20at%2031%20December%202025%20%20Annex%202.pdf", 0, "relevant product rows", "Complete seven-page licence list reviewed; no marketed lubricant or technical-fluid row", "reviewed_zero_relevant_product_rows"),
    ("NSI certified products", "Namibia / current directory", "Official government product-certification directory", "https://www.nsi.com.na/wp-content/uploads/2024/08/Directory-of-Certified-products.pdf", 0, "relevant product rows", "Current one-page product directory contains two cement licences only; Vivo Energy lubricant warehousing appears only in a separate ISO 9001 organization scope", "reviewed_zero_relevant_product_rows"),
    ("Brava Lubricants", "Puerto Rico / US English", "Official manufacturer product pages and technical documents", "https://bravalubricants.com/products/view-catalog/", 69, "current product-grade rows", "Thirty product pages; 48 rows with SAE, seven with ISO VG, 94 package occurrences and 93 part-number values; one cross-product part-number collision, one nonstandard ACEA value and source placeholders explicitly flagged", "ingested_and_verified_attributed_factual_fields"),
    ("GSA certified lubricant products", "Ghana", "Official government product-certification PDF", "https://gsa.gov.gh/wp-content/uploads/2018/04/2025-CERTIFIED-LIST-JAN.-SEP.pdf", 16, "certified product rows", "January-September 2025 register: 13 engine oils, two gear oils and one radiator coolant with brand/product, SAE/API where reported, standard, licence and validity dates", "ingested_and_verified"),
    ("GSA certified clients", "Ghana", "Official government system-certification search", "https://www.gsa.gov.gh/CertificationSearch.php", None, None, "Current public search is for system-certified clients and does not expose a bulk product/SKU directory", "reviewed_not_a_product_catalog"),
    ("Motul", "Global", "Corporate disclosure", "https://cms.motul.com/images/DPEF_2024_english_e9953e284f.pdf", 19000, "active references", "Also reports more than 400 formulations; references are not normalized products; catalog extraction requires written permission", "count_evidence_only_permission_required"),
    ("IndianOil SERVO", "India / 35+ export countries", "Official state-owned manufacturer disclosure", "https://iocl.com/pages/servo-lubes-and-greases-overview", 1600, "marketed grades", "Official disclosure also reports 5,200+ formulations and 1,700+ active SKUs; website terms require prior written permission for republication", "count_evidence_only_permission_required"),
    ("Wolf Lubricants", "Global / 27 locale variants", "Official daily product sitemap and product cards", "https://docs.wolfoil.com/en-us", 391, "unique branded product identities", "Exactly 391 IDs with suffix -01 observed 2026-07-21; terms prohibit substantial database reuse for any purpose", "written_permission_required"),
    ("Champion Lubricants", "Global / 27 locale variants", "Official daily product sitemap and product cards", "https://www.championlubes.com/en-us/products", 431, "unique branded product identities", "Exactly 431 IDs with suffix -02 observed 2026-07-21; same Wolf Oil Corporation database-reuse restriction", "written_permission_required"),
    ("LIQUI MOLY", "Global English / 2020 historical", "Official downloadable PDF product catalog", "https://www.liqui-moly.com/fileadmin/user_upload/Downloads/Technische_Informationen/Kataloge_und_Prospekte/EN/5603.pdf", 419, "normalized product rows", "204-page document dated 2020-04-23; 1,482 unique part numbers; lifecycle historical/unverified; factual fields only", "ingested_and_verified_historical_factual_fields_only"),
    ("LIQUI MOLY", "GB English / current 2026", "Official XML sitemap + public OpenAPI", "https://www.liqui-moly.com/sitemap/www.liqui-moly.com/sitemap_gb_en.xml", 447, "normalized lubricant and technical-fluid master products", "759 sitemap product URLs; 742 resolved by API; 447 in professional scope; 985 article SKUs; factual fields only; explicit 2020→2026 lifecycle audit", "ingested_and_verified_current_factual_fields_only"),
    ("Castrol", "Global / market-specific", "Official product finder", "https://www.castrol.com/en/global/corporate/products.html", None, None, "Automotive and industrial ranges; market variants must be retained", "discovery"),
    ("MOLYKOTE / DuPont", "Global / location-filtered", "Official product finder", "https://www.dupont.com/solution-finder/results.html?BU=molykote", 170, "finder results", "Terms prohibit page-scrape/copying; written permission or licensed feed required", "permission_or_licensed_feed_required"),
    ("Klüber Lubrication", "Global / market-specific", "Official products", "https://www.klueber.com/global/en/products-service/products/", None, None, "Terms explicitly prohibit data mining, robots, scraper and offline reader", "permission_or_licensed_feed_required"),
    ("SKF", "Global", "Maintenance and lubrication products", "https://www.skf.com/group/products/maintenance-products/lubrication-management", None, None, "Greases, oils and lubrication-system consumables; exclude equipment", "discovery"),
    ("Petro-Canada Lubricants", "Global / market-specific", "Official products", "https://lubricants.petro-canada.com/en-ca/products", None, None, "Terms prohibit screen scraping without express permission", "permission_or_licensed_feed_required"),
    ("Chevron Lubricants", "Global / market-specific", "Official products", "https://www.chevronlubricants.com/en_us/home/products.html", None, None, "Delo, Havoline and industrial products", "discovery"),
    ("Valvoline", "Global / market-specific", "Official current product catalog", "https://www.valvolineglobal.com/en/products/", None, None, "Current product pages expose grades and specifications, but the published Terms of Use restrict copying and reproduction to personal, non-commercial or non-profit educational use", "written_permission_or_official_feed_required"),
    ("Lubrax", "Brazil / current domestic catalog", "Official current product catalog and technical-document directory", "https://www.lubrax.com.br/produtos", 149, "current TDS documents observed", "The official catalog exposed 149 TDS and 824 SDS files at review; published terms prohibit reproduction or distribution beyond personal use without written authorization, and ANP registration evidence is already represented separately", "written_permission_or_official_feed_required"),
    ("PETRONAS Lubricants", "Global / market-specific", "Official current product catalog and datasheets", "https://global.pli-petronas.com/products", None, None, "Indexed pages expose FG codes and professional specifications, but CloudFront blocks catalog/PDF/sitemap/robots retrieval from the research environment; no protection bypassed", "official_feed_allowlist_and_written_permission_required"),
    ("ENEOS", "Japan / English current catalog", "Official product pages and PDS", "https://www.eneos.co.jp/english/products/lubricants/", 481, "displayed product occurrences / 467 unique names", "Seven pages: automotive 21, fleet 32, industrial 194, metalworking 124, greases 53, marine 27, private-use engines 30; terms require prior written permission beyond personal use", "written_permission_or_official_feed_required"),
    ("Idemitsu", "Global / market-specific", "Official lubricants product search", "https://www.idemitsu.com/en/business/lube/products/index.html", None, None, "Automotive, industrial, marine and grease ranges are searchable, but official Website Usage Guidelines prohibit reproduction or duplication without prior written consent", "written_permission_or_official_feed_required"),
    ("Repsol", "Global / market-specific", "Official lubricants", "https://lubricants.repsol.com/en/products/", None, None, "Automotive and industrial product ranges", "discovery"),
    ("Gulf Oil", "Global PDS directory", "Official current product data sheet directory", "https://pds.gulfoilltd.com/prodoemsearchresult", 226, "PDS listing rows / 200 unique displayed names", "Thirty-eight segments and 226 distinct PDS URLs; terms permit copying only for reasonable personal use and prohibit all other use", "written_permission_or_official_feed_required"),
    ("Sinopec Lubricant", "Global / market-specific", "Official products", "https://www.sinopeclube.com/", None, None, "Automotive and industrial products; multilingual source review needed", "discovery"),
    ("DEUTZ DQC", "Global OEM approvals", "Official oil and coolant release lists", "https://www.deutz.com/germany/en/parts-service/operating-liquids/technical-information/", None, None, "Current issue 07/2026 located; copyright notice requires permission for transformed/commercial reuse", "permission_or_licensed_feed_required"),
    ("Detroit / Daimler Truck DFS", "North America / global suppliers", "Official approved-fluids PDF lists", "https://dtnacontent-dtna.prd.freightliner.com/content/public/dtnaportalpublic/LubricantsFuelsCoolants.html", 661, "approval occurrences", "11 current lists dated 2026-07-09; terms restrict reuse to noncommercial personal use, therefore products are not ingested", "written_permission_required"),
    ("CPC Corporation Taiwan", "Taiwan / current domestic catalog", "Official state-owned manufacturer directory and open-government datasets", "https://cpclube.cpc.com.tw/News_eBook.aspx?PageSize=1000&_CSN=0&n=7478&page=1&sms=12330", 224, "current product-grade cards", "Seven categories; 224 unique manufacturer product codes; 478 structured package offers; factual fields published under Taiwan Open Government Data License 1.0", "ingested_and_verified_current_factual_fields_only"),
    ("FUCHS Saudi Arabia", "Saudi Arabia", "Official embedded product finder", "https://www.fuchs.com/sa/en/products/service-links/product-finder/", 360, "normalized product rows", "376 embedded rows; 13 series and two placeholders excluded; one duplicate merged; imprint permits informational organisational copying with the full copyright notice", "ingested_and_verified_informational_factual_fields_only"),
    ("FUCHS Macedonia", "North Macedonia", "Official embedded product finder", "https://www.fuchs.com/mk/en/products/service-links/product-finder/", 948, "normalized product rows", "1,075 embedded rows; 97 series and six equipment rows excluded; 24 duplicates merged; imprint permits informational organisational copying with the full copyright notice", "ingested_and_verified_informational_factual_fields_only"),
]


FIELDS = [
    ("identity", "source_product_id; manufacturer; brand; product_line; product_name; grade; market; status"),
    ("classification", "family; product_form; application; industry; standardized_name; technical_profile_id; proposed_enkt"),
    ("performance", "SAE; API; ACEA; ISO_VG; DIN; ISO_class; ASTM; GOST; OEM_approvals"),
    ("composition", "base_oil; thickener; NLGI; coolant_chemistry; petroleum_share; physical_state"),
    ("operating limits", "temperature_min_c; temperature_max_c; viscosity_40c; viscosity_100c; viscosity_index"),
    ("trade and state codes", "SKP; IKPU; TNVED_candidates; ENKT_current; unit; package; conversion_to_kg"),
    ("provenance", "source_url; TDS_url; SDS_url; source_date; valid_from; valid_to; extraction_method; evidence_hash"),
    ("quality", "confidence; review_status; reviewer; duplicate_cluster; canonical_product_id; validation_notes"),
]


ESTIMATES = [
    ("Normalized formulation-grade-market", "Brand + formulation + grade + market; package sizes excluded", 150000, 400000, 250000, "Primary analytical catalog and ENKT mapping layer"),
    ("Global commercial SKU/reference", "Country + package + label/language + sellable reference retained", 1000000, 3000000, 1800000, "Procurement and price-observation layer"),
    ("Unique technical profiles", "Brand-independent professional equivalence classes", 3000, 12000, 6000, "Candidate ENKT extension after expert validation"),
]


RULES = [
    (1, "Never overwrite source wording", "Keep raw product name, market and source snapshot alongside normalized values"),
    (2, "One canonical product is not one package", "Bottle, drum and IBC are offers/SKUs linked to the same product formulation"),
    (3, "Market variants remain visible", "Merge only when formula, grade, approvals and manufacturer identity are demonstrably the same"),
    (4, "Series is not a grade", "Mobil SHC 600 is a series; SHC 626 and SHC 630 are separate product-grade rows"),
    (5, "Approval beats marketing similarity", "Equivalence requires the professional key for the family, not name or viscosity alone"),
    (6, "Sources and rights are mandatory", "Use official pages, licensed feeds or permitted access; respect robots, terms and rate limits"),
    (7, "Lifecycle is versioned", "Active, superseded, discontinued and historical products are retained with validity dates"),
    (8, "Counts are reproducible", "Publish counts by grain, date, source, market, duplicate state and validation status"),
]


def style(ws) -> None:
    fill = PatternFill("solid", fgColor="17365D")
    for cell in ws[1]:
        cell.fill = fill
        cell.font = Font(color="FFFFFF", bold=True)
        cell.alignment = Alignment(wrap_text=True, vertical="center")
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions
    for column in ws.columns:
        letter = get_column_letter(column[0].column)
        ws.column_dimensions[letter].width = min(70, max(12, max(len(str(c.value or "")) for c in column) + 2))
    for row in ws.iter_rows(min_row=2):
        for cell in row:
            cell.alignment = Alignment(vertical="top", wrap_text=True)


def add(wb, title, headers, rows):
    ws = wb.create_sheet(title)
    ws.append(headers)
    for row in rows:
        ws.append(row)
    style(ws)
    return ws


def main() -> None:
    wb = Workbook()
    wb.remove(wb.active)
    add(wb, "01_Паспорт", ["Показатель", "Значение"], [
        ("Статус", "Стартовый реестр источников; не завершённая мировая выгрузка"),
        ("Дата среза", date.today().isoformat()),
        ("Главная единица строки", "Brand + formulation + grade + market, без фасовки"),
        ("Плановое ядро", "250 000 нормализованных строк; рабочий диапазон 150 000–400 000"),
        ("Отдельный SKU-слой", "1,0–3,0 млн строк с рынками, языками и фасовками"),
        ("Критерий завершения", "Все источники имеют дату обхода; новые источники два цикла подряд дают <0,5% новых canonical products"),
        ("Ограничение", "Точный итог неизвестен до обхода, правовой проверки доступа и дедупликации"),
    ])
    add(wb, "02_Источники", ["Компания/бренд", "Рынок", "Источник", "URL", "Наблюдаемое число", "Единица числа", "Примечание", "Статус"], SOURCES)
    add(wb, "03_Оценка_объёма", ["Слой", "Гранулярность", "Минимум", "Максимум", "Плановый ориентир", "Назначение"], ESTIMATES)
    add(wb, "04_Схема_данных", ["Блок", "Поля"], FIELDS)
    add(wb, "05_Дедупликация", ["№", "Правило", "Реализация"], RULES)
    add(wb, "06_Этапы", ["Этап", "Результат", "Контроль"], [
        ("A. Реестр производителей", "Страны, бренды, владельцы, официальные каталоги", "URL, рынок, права доступа, дата"),
        ("B. Получение", "Raw snapshots и документы TDS/PDS/SDS", "Хэш, HTTP metadata, parser version"),
        ("C. Нормализация", "Единые семейства и профессиональные признаки", "Family-specific validation"),
        ("D. Дедупликация", "Canonical products + market offers + packages", "Explainable merge/split decisions"),
        ("E. Кодирование", "Связи ENKT–SKP–IKPU–TNVED", "Source, confidence, reviewer, validity"),
        ("F. Публикация", "Версионированный открытый каталог", "Coverage dashboard and reproducible counts"),
    ])
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    wb.save(OUTPUT)
    print(f"sources={len(SOURCES)} output={OUTPUT}")


if __name__ == "__main__":
    main()
